name: godd
version: 1.0
vendor: Michael Vogt <mvo@ubuntu.com>
binaries:
  - name: ./bin/godd
summary: Simple dd like tool
description: written in go so it is self contained and really portable, you would need to use hw-assign to access devices.
icon: icon.png

parts:
  godd:
    type: go-project
    source: git://github.com/mvo5/godd
build-packages: 
    - libgudev-1.0-dev
