name: spongeshaker
version: 0
vendor: Michael Vogt <michael.vogt@ubuntu.com>
binaries:
 - name: bin/sha3sum
summary: A python sha3 implementation
description: A python2 project using snapcraft

parts:
  spongeshaker:
    plugin: python3-project
    source: git://github.com/markokr/spongeshaker.git
  sha3:
    plugin: copy
    files:
     sha3sum.py: bin/sha3sum
