name: ros
version: 1.0
vendor: Number Nine <number-nine@is-alive.com>
summary: A robot example
icon: icon.svg
description: A really small ros examples

parts:
  roscore:
    type: roscore
  catkin-tutorials:
    source: git://github.com/ros/catkin_tutorials.git
    type: catkin
