name: ros-example
version: 1.0
vendor: Number Five <number-five@is-alive.com>
summary: A robot example
icon: icon.svg
description: A really small ros examples
binaries:
  listener:
    exec: opt/ros/indigo/beginner_tutorials/lib/beginner_tutorials/listener
  talker:
    exec: opt/ros/indigo/beginner_tutorials/lib/beginner_tutorials/talker

parts:
  roscore:
    plugin: roscore
  catkin-tutorials:
    plugin: catkin
    source: .
    catkin-packages:
      - beginner_tutorials
