name: ros-example
version: 1.0
vendor: Number Nine <number-nine@is-alive.com>
summary: A robot example
icon: icon.svg
description: A really small ros examples

parts:
  roscore:
    type: roscore
  catkin-tutorials:
    source: .
    type: catkin
    catkin-pkg: beginner_tutorials

binaries:
  listener:
    exec: opt/ros/jade/lib/beginner_tutorials/listener
  talker:
    exec: opt/ros/jade/lib/beginner_tutorials/talker
