name: ros-example
version: 1.0
vendor: Number Five <number-five@is-alive.com>
summary: A robot example
icon: icon.svg
description: A really small ros examples

parts:
  roscore:
    type: roscore
  catkin-tutorials:
    source: .
    type: catkin
    catkin-packages:
      - beginner_tutorials

binaries:
  listener:
    exec: opt/ros/indigo/lib/beginner_tutorials/listener
  talker:
    exec: opt/ros/indigo/lib/beginner_tutorials/talker
