name: ros-example
version: 1.0
vendor: Number Five <number-five@is-alive.com>
summary: A robot example
icon: icon.svg
description: A really small ROS example

parts:
  roscore:
    plugin: roscore

services:
  rosmaster:
    start: bin/roscore-rosmaster-service
    description: ROS Master Service
    ports:
      internal:
        rosmaster:
          port: 11311/tcp
          negotiable: false
