name: shout
version: 0.52.0
vendor: Sergio Schvezov <sergio.schvezov@canonical.com>
summary: A self hosted web IRC client
description: This example is not really production quality
icon: icon.png

services:
  server:
    start: bin/shout.sh
    description: shout irc service

parts:
  shout:
    plugin: nodejs
    node-packages:
      - shout
  wrapper:
    plugin: copy
    files:
      shout.sh: bin/shout.sh
