name: qmldemo
version: 1
vendor: Ted Gould <ted@canonical.com>
architecture: amd64
frameworks: [mir]
binaries:
  - name: qmldemo
    exec: qmlscene demo.qml --
    caps:
      - mir_client
      - network-client
