parts:
    golang-static-http:
        plugin: go1.4-project
        source: git://github.com/mikix/golang-static-http
    fswebcam:
        plugin: ubuntu
    glue:
        plugin: copy
        files:
            webcam-webui: bin/webcam-webui
snappy-metadata: meta
