name: webcam-webui
version: 1.0.0
vendor: Loïc Minier <loic.minier@ubuntu.com>
services:
 - name: webcam-webui
   start: bin/webcam-webui
   security-template: unconfined
summary: Webcam web UI
description: Exposes your webcam over a web UI
icon: icon.png

parts:
    golang-static-http:
        type: go-project
        source: git://github.com/mikix/golang-static-http
    glue:
        type: copy
        stage-packages:
          - fswebcam
        files:
            webcam-webui: bin/webcam-webui
