name: wget
version: 0
vendor: Michael Terry <mterry@ubuntu.com>
binaries:
    - name: usr/bin/wget
summary: wget for snappy
description: a basic example from ubuntu packages

parts:
  wget:
    plugin: ubuntu
