name: tomcat-webapp-demo
vendor: Loïc Minier <loic.minier@ubuntu.com>
version: 1.0
architectures:
 - amd64
services:
 tomcat:
   start: bin/wrapper
   caps:
   - networking
   - network-service
summary: Demo of Tomcat-hosted Webapp
description: This is a demo snap of a Tomcat-hosted webapp produced by snapcraft with maven.
icon: icon.png

parts:
    webapp:
        type: maven-project
        source: git://github.com/lool/snappy-mvn-demo.git
    tomcat:
        type: tar-content
        source: http://mirrors.ircam.fr/pub/apache/tomcat/tomcat-8/v8.0.26/bin/apache-tomcat-8.0.26.tar.gz
    local-files:
        type: make-project
        source: .
