parts:
    webapp:
        plugin: maven-project
        source: git://github.com/lool/snappy-mvn-demo.git
    tomcat:
        plugin: tar-content
        source: http://mirrors.ircam.fr/pub/apache/tomcat/tomcat-8/v8.0.24/bin/apache-tomcat-8.0.24.tar.gz
    wrapper:
        plugin: copy
        files:
            tomcat-wrapper: bin/tomcat
snappy-metadata: meta
