name: java-hello-world
version: 0
vendor: Michael Terry <mterry@ubuntu.com>
binaries:
 hello:
   exec: bin/wrapper
summary: A java example
description: this is not much more than an example
icon: icon.png

parts:
    local:
        plugin: ant-project
        source: .
    wrapper:
        plugin: make-project
        source: .
