name: java-hello-world
version: 0
vendor: Michael Terry <mterry@ubuntu.com>
binaries:
 - name: hello
   exec: bin/wrapper
summary: A java example
description: this is not much more than an example
icon: icon.png

parts:
    local:
        type: ant-project
        source: .
    wrapper:
        type: make-project
        source: .
