name: spongeshaker
version: 0
vendor: Michael Vogt <michael.vogt@ubuntu.com>
binaries:
 - name: ./bin/sha3sum
summary: A python sha3 implementation
description: A python2 project using snapcraft
icon: icon.png

parts:
  spongeshaker:
    type: python2-project
    source: git://github.com/markokr/spongeshaker.git
  make-project:
    source: .
