name: webcam-webui
version: 1
vendor: Vendor <email@example.com>
summary: Webcam web UI
description: Exposes your webcam over a web UI
icon: icon.png
services:
  - name: webcam-webui
    start: bin/webcam-webui

parts:
  cam:
    type: go-project
    source: git://github.com/mikix/golang-static-http
    stage-packages:
      - fswebcam
    filesets:
      fswebcam:
        - usr/bin/fswebcam
        - lib
        - usr/lib
      go-server:
        - bin/golang-*
    snap:
      - $fswebcam
      - $go-server
  glue:
    type: copy
    files:
      webcam-webui: bin/webcam-webui

