name: tomcat-webapp-demo
vendor: Loïc Minier <loic.minier@ubuntu.com>
version: 1.0
architectures:
 - amd64
services:
 - name: tomcat
   start: bin/wrapper
   caps:
   - networking
   - network-service

