name: downloader
version: 1.0
vendor: "Sergio Schvezov <sergio.schvezov@canonical.com>"
summary: curl based downloaded
description: this is an example package
icon: icon.png
binaries:
    - name: bin/test

parts:
    main:
        type: make-project
        source: .
        after:
            - curl
