name: awsiot-demo
vendor: Maarten Ectors <maarten.ectors@canonical.com>
version: 1.0
summary: Demo of AWSCLI SDK
description: This is a demo snap to include the AWS CLI.
icon: icon.svg
binaries:
    mttqclient:
        exec: bin/mqttclient.py
parts:
    awscli:
        plugin: awscli
        accesskeyid: <key goes here>
        secretaccesskey: <secret goes here>
        region: us-east-1
    awsiot:
        plugin: awsiot
        generatekeys: True
        policyname: PubSubToAnyTopic
        thing: MyThing
        after:
          - awscli
    pythonmqtt:
        plugin: python3-project
        requirements: mqttdependencies
    mqttclient:
        plugin: copy
        source: .
        files:
            mqttclient.py: bin/mqttclient.py
